# Generated by Django 5.2.4 on 2025-07-23 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0004_order_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
    ]
